name: Deploy to S3

on:
  push:
    branches: [ "master" ]

permissions:
  id-token: write   # needed for OIDC
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::833476995316:role/github-actions-deployer
          aws-region: us-east-1

      - name: Sync to S3
        run: |
          aws s3 sync . s3://rrdental \
            --delete \
            --only-show-errors \
            --exclude ".git/*" \
            --exclude ".github/*" \
            --exclude ".gitignore" \
            --exclude "node_modules/*" \
            --exclude "package-lock.json" \
            --exclude ".env" \
            --exclude ".env.*" \
            --exclude "README.md" \
            --exclude "LICENSE"
